## Required global project information to be created in secret
secret:
  data:
    PROJECT_ID: 1000
    PROJECT_NAME: exampe
    POSTGRES_PASSWORD: xxxx

## Required docker registry information to pull images from
imageCredentials:
  data:
    username: "xxxxxx-951af420-xxxxxx"
    password: "xxxxxx-R518xxxxxxxx"

## Installing the Ingress Controller
ingressController:
  enabled: false

## Required exsiting or new PVC to be created
shared:
  persistentVolume:
    existingClaim: "qmig-shared"

ingress:
  enabled: false
  className: "nginx"
  host: "example.internal"

httpRoutes:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-gateway
  parentRefs:
    - name: qmig-gateway
      namespace: ns-admin
      sectionName: http
    - name: qmig-gateway
      namespace: ns-admin
      sectionName: https-admin
  ## @param httpRoutes.hostnames hostnames in routes record Default: []
  hostnames:
    - "example.internal"
  ## @param httpRoutes.redirectHttp create redirect filter http to https Default: false
  redirectHttp: true