{{- if .Values.wbdba.enabled }}
{{- $nodeSelector := .Values.wbdba.nodeSelector }}
{{- $affinity := .Values.wbdba.affinity }}
{{- $tolerations := .Values.wbdba.tolerations }}
{{- $securityContext := include "podSecurityContext" (list . .Values.tests) }}
{{- $containerSecurityContext := include "containerSecurityContext" (list . .Values.tests) }}
{{- $pvcTemp := printf "%s-%s" (include "qmig.wbdba.fullname" .) "empty" -}}
{{- $pvc := include "qmig.pv.shared" . -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "qmig.wbdba.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qmig.wbdba.labels" . | nindent 4 }}
  {{- with .Values.wbdba.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  concurrencyPolicy: {{ .Values.wbdba.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.wbdba.failedJobsHistoryLimit }}
  schedule: {{ .Values.wbdba.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.wbdba.successfulJobsHistoryLimit }}
  startingDeadlineSeconds: {{ .Values.wbdba.startingDeadlineSeconds }}
  suspend: true
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.wbdba.ttlSecondsAfterFinished }}
      backoffLimit: {{ .Values.wbdba.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "qmig.wbdba.labels" . | nindent 12 }}
          {{- with .Values.wbdba.podAnnotations }}
          annotations: {{ toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- include "qmig.dockerauthList" (list . .Values.tests) | indent 10 }}
          securityContext: {{ $securityContext | nindent 12 }}
          nodeSelector: {{- toYaml $nodeSelector | nindent 12 }}
          affinity: {{- toYaml $affinity | nindent 12 }}
          tolerations: {{- toYaml $tolerations | nindent 12 }}
          serviceAccountName: {{ template "qmig.serviceAccount" . }}
          containers:
            - name: {{ include "qmig.wbdba.name" . }}
              image: "{{ .Values.wbdba.image.repository }}:{{ .Values.wbdba.image.tag }}"
              imagePullPolicy: {{ .Values.wbdba.image.pullPolicy }}
              securityContext: {{ $containerSecurityContext | nindent 16 }}
              resources:
                {{- toYaml .Values.wbdba.resources | nindent 16 }}
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                {{- include "qmig.project.env" . | nindent 16 }}
                {{- with .Values.wbdba.env -}}
                {{- toYaml . | nindent 16 }}
                {{- end -}} 
                {{- range .Values.wbdba.envSecret }}
                - name: {{ .name }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .secretRef }}
                      key: {{ .secretKey }}
                {{- end }}
              volumeMounts:
                {{- include "qmig.wbdba.volumeMounts" (dict "Values" .Values "pvcname" $pvc "pvctemp" $pvcTemp ) | indent 16 }}
              {{- if .Values.wbdba.extraVolumeMounts }}
                {{- toYaml .Values.wbdba.extraVolumeMounts | nindent 16 }}
              {{- end }}
          restartPolicy: {{ .Values.wbdba.restartPolicy }}
          volumes:
          {{- include "qmig.shared.volume" (dict "Values" .Values "pvcname" $pvc "pvctemp" $pvcTemp ) | indent 12 }}
          {{- if .Values.wbdba.extraVolumes }}
            {{- toYaml .Values.wbdba.extraVolumes | nindent 12 }}
          {{- end }}
{{- end }}